// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgF8XQHQwC2Ii-oIYx5eldipefSG70r00',
    appId: '1:804928236699:web:12fa5ae20b1e6b8ce72a3e',
    messagingSenderId: '804928236699',
    projectId: 'todo-c6754',
    authDomain: 'todo-c6754.firebaseapp.com',
    storageBucket: 'todo-c6754.firebasestorage.app',
    measurementId: 'G-LBDDRM66YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAblrDDat-hb48m_Raxf0ASMqcA01Z7uLg',
    appId: '1:804928236699:android:7b01f85748ec00f7e72a3e',
    messagingSenderId: '804928236699',
    projectId: 'todo-c6754',
    storageBucket: 'todo-c6754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ_WwqnbXZoi6QOd8fc6DqWY7Zium6xxk',
    appId: '1:804928236699:ios:7f87ebc3447573a7e72a3e',
    messagingSenderId: '804928236699',
    projectId: 'todo-c6754',
    storageBucket: 'todo-c6754.firebasestorage.app',
    iosBundleId: 'com.example.firebasetodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ_WwqnbXZoi6QOd8fc6DqWY7Zium6xxk',
    appId: '1:804928236699:ios:7f87ebc3447573a7e72a3e',
    messagingSenderId: '804928236699',
    projectId: 'todo-c6754',
    storageBucket: 'todo-c6754.firebasestorage.app',
    iosBundleId: 'com.example.firebasetodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgF8XQHQwC2Ii-oIYx5eldipefSG70r00',
    appId: '1:804928236699:web:7aaa6744176a98b8e72a3e',
    messagingSenderId: '804928236699',
    projectId: 'todo-c6754',
    authDomain: 'todo-c6754.firebaseapp.com',
    storageBucket: 'todo-c6754.firebasestorage.app',
    measurementId: 'G-PGQNYJC0TK',
  );
}
